# Generated by Django 4.2.13 on 2024-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sale_expenditure_alter_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
